# Generated by Django 5.1.1 on 2024-09-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='category',
        ),
    ]
