# Generated by Django 5.1.1 on 2024-09-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0002_rename_genre_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='book_id',
        ),
    ]
