# Generated by Django 5.1.1 on 2024-09-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0003_rename_id_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
