# Generated by Django 5.1.1 on 2024-09-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0005_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
