# Generated by Django 5.1.1 on 2024-09-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0006_alter_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='book_id',
            new_name='user_id',
        ),
    ]
