# Generated by Django 5.1.1 on 2024-09-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0007_rename_book_id_users_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
