# Generated by Django 5.1.1 on 2024-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0009_user_created_at_user_updated_at_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
    ]
