# Generated by Django 5.1.1 on 2024-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Library', '0011_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
